name: Deploy FastAPI to Cloud Run

on:
  push:
    branches: [main]
    paths: 
      - 'api/**'  # Trigger only when API code changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push API Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: |
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-fastapi-app:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: my-fastapi-app
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-fastapi-app:latest
          region: us-central1
          memory: 1Gi
          timeout: 900
          allow-unauthenticated: true