name: CI/CD Pipeline

on:
  push:
    branches: [staging, main]
    paths: 
      - 'api/**'

jobs:
  test-and-deploy-staging:
    # Only run when pushing to staging branch
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          pip install -r api/requirements.txt
          pytest tests/

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: |
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-fastapi-app:${{ github.sha }}-staging

      - name: Deploy to Staging
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: my-fastapi-app-staging
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-fastapi-app:${{ github.sha }}-staging
          region: us-central1

  deploy-prod:
    # Only run when pushing to main branch
    if: github.ref == 'refs/heads/main'
    needs: test-and-deploy-staging  # Wait for staging tests
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Promote staging image to prod
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: my-fastapi-app  # Your existing production service
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-fastapi-app:${{ github.sha }}-staging
          region: us-central1